export interface DailyChallenge {
    id: number;
    icon: string;
    theme: string;           // 챌린지 이름
    strategy: string;        // 마케팅 전략 개념
    description: string;     // 과제 설명
    tip: string;             // 실전 팁
    keywords: string[];      // 캡션 매칭 힌트
    bonusXP: number;
    bonusPoints: number;
}

export const DAILY_CHALLENGES: DailyChallenge[] = [
    {
        id: 1,
        icon: "💛",
        theme: "감성 스토리텔링",
        strategy: "Emotional Marketing",
        description: "제품의 기능이 아닌 감정을 팔아보세요. 이 제품을 쓰는 사람의 이야기를 써보세요.",
        tip: "\"이 가방을 들고 처음 학교에 간 날...\" 처럼 스토리로 시작하면 클릭률 3배!",
        keywords: ["이야기", "기억", "추억", "처음", "설레", "감동", "특별"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 2,
        icon: "⏰",
        theme: "FOMO 마케팅",
        strategy: "Fear of Missing Out",
        description: "한정 수량, 기간 한정으로 지금 바로 사야 하는 이유를 만들어보세요.",
        tip: "\"오늘만\", \"딱 10개\", \"내일이면 끝\" — 수량과 시간이 구매를 부릅니다.",
        keywords: ["한정", "마감", "오늘만", "품절", "마지막", "한정판", "지금"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 3,
        icon: "💰",
        theme: "가성비 어필",
        strategy: "Value Proposition",
        description: "이 가격에 이 품질? 구체적인 숫자로 얼마나 이득인지 보여주세요.",
        tip: "\"카페 커피 3잔 값으로 한 달 사용!\" — 비교 대상이 있으면 더 설득력 있어요.",
        keywords: ["가성비", "저렴", "가격", "원", "할인", "절약", "이득", "싸"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 4,
        icon: "📝",
        theme: "사용 후기 형식",
        strategy: "Social Proof",
        description: "실제로 써본 사람처럼 솔직하게 써보세요. 장점과 아쉬운 점도 함께.",
        tip: "100% 칭찬보다 \"단점도 있지만 그래도\"가 더 신뢰를 줍니다.",
        keywords: ["후기", "써봤어", "사용해보니", "솔직히", "리뷰", "써보니", "진짜"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 5,
        icon: "✨",
        theme: "라이프스타일 연출",
        strategy: "Lifestyle Marketing",
        description: "제품이 아닌 이 제품을 쓰는 멋진 일상을 보여주세요.",
        tip: "\"이 텀블러를 들고 카페 작업하는 아침\" — 제품보다 장면을 팔아요.",
        keywords: ["일상", "라이프", "스타일", "아침", "카페", "여행", "데일리"],
        bonusXP: 50,
        bonusPoints: 32000,
    },
    {
        id: 6,
        icon: "🎯",
        theme: "문제-해결 프레임",
        strategy: "Problem-Solution",
        description: "고객의 불편함을 먼저 공감하고, 이 제품이 해결사임을 보여주세요.",
        tip: "\"항상 가방이 무거워서 고민이었는데...\" 공감 → 해결의 흐름이 핵심.",
        keywords: ["고민", "불편", "해결", "문제", "드디어", "찾았다", "답"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 7,
        icon: "📊",
        theme: "숫자로 설득하기",
        strategy: "Data-Driven Marketing",
        description: "구체적인 숫자와 데이터로 신뢰를 만들어보세요.",
        tip: "\"98% 만족\", \"3초만에 충전\" — 모호한 말 대신 수치가 신뢰를 줍니다.",
        keywords: ["퍼센트", "%", "개", "명", "시간", "초", "일", "배"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 8,
        icon: "🌿",
        theme: "가치 소비 어필",
        strategy: "Cause Marketing",
        description: "이 제품을 사면 환경, 사회, 지역에 어떤 좋은 일이 생기는지 알려주세요.",
        tip: "\"이 제품 1개 판매 시 나무 1그루 심어요\" — 구매가 선행이 되는 순간.",
        keywords: ["환경", "친환경", "지속가능", "기부", "기여", "에코", "제로웨이스트"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 9,
        icon: "🔄",
        theme: "비포/애프터",
        strategy: "Transformation Story",
        description: "이 제품을 쓰기 전과 후의 변화를 극적으로 보여주세요.",
        tip: "변화가 클수록 임팩트가 커요. 구체적인 상황 변화를 묘사해보세요.",
        keywords: ["전", "후", "변화", "달라진", "바뀐", "전후", "비포", "애프터"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 10,
        icon: "🌸",
        theme: "시즌 트렌드 연계",
        strategy: "Seasonal Marketing",
        description: "지금 이 시기, 이 계절에 딱 맞는 이유를 만들어보세요.",
        tip: "\"봄맞이\", \"방학 특집\" — 타이밍을 잘 잡은 콘텐츠는 자연스럽게 퍼집니다.",
        keywords: ["봄", "여름", "가을", "겨울", "방학", "졸업", "시즌", "날씨"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 11,
        icon: "#️⃣",
        theme: "해시태그 전략",
        strategy: "Hashtag Optimization",
        description: "검색에 잘 걸리는 해시태그 5개 이상을 전략적으로 선택해보세요.",
        tip: "너무 대중적인 태그(#일상)보다 중간 규모 태그(#에코라이프)가 노출에 유리해요.",
        keywords: ["#", "태그", "해시태그", "검색"],
        bonusXP: 35,
        bonusPoints: 20000,
    },
    {
        id: 12,
        icon: "🧑‍🤝‍🧑",
        theme: "타겟 고객에게 직접",
        strategy: "Persona Targeting",
        description: "이 제품을 가장 필요로 하는 딱 한 사람에게 직접 말을 거는 글을 써보세요.",
        tip: "\"수능 끝난 고3 여러분께\" — 타겟이 좁을수록 그 사람에게는 더 크게 와닿아요.",
        keywords: ["여러분", "당신", "님", "분들", "학생", "직장인", "엄마", "아빠"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 13,
        icon: "📖",
        theme: "브랜드 스토리",
        strategy: "Brand Storytelling",
        description: "이 제품이 어떻게 만들어졌는지, 어떤 마음으로 팔고 있는지 이야기해보세요.",
        tip: "창업 동기, 만든 사람의 철학 — 스토리가 있는 브랜드는 기억에 남아요.",
        keywords: ["이야기", "시작", "만들었", "우리", "브랜드", "철학", "처음"],
        bonusXP: 55,
        bonusPoints: 35000,
    },
    {
        id: 14,
        icon: "🎬",
        theme: "사용법 튜토리얼",
        strategy: "Educational Marketing",
        description: "이 제품을 100% 활용하는 꿀팁을 알려주는 콘텐츠를 만들어보세요.",
        tip: "\"이렇게 쓰면 2배 효과\" — 몰랐던 사용법은 공유 욕구를 자극해요.",
        keywords: ["방법", "팁", "꿀팁", "사용법", "활용", "이렇게", "알려드려요"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 15,
        icon: "💬",
        theme: "참여 유도 콘텐츠",
        strategy: "Engagement Marketing",
        description: "댓글이나 반응을 유도하는 질문이나 참여 요소를 넣어보세요.",
        tip: "\"댓글로 알려주세요\", \"이 중 뭐가 더 좋아요?\" — 참여가 바이럴을 만들어요.",
        keywords: ["댓글", "알려주세요", "투표", "어떤", "좋아요", "여러분은", "의견"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 16,
        icon: "🤝",
        theme: "콜라보 마케팅",
        strategy: "Co-Marketing",
        description: "이 제품과 함께 쓰면 더 좋은 다른 제품/서비스를 연계해서 소개해보세요.",
        tip: "\"이 커피와 함께라면\" — 연관 제품과의 조합이 새로운 가치를 만들어요.",
        keywords: ["함께", "같이", "조합", "페어링", "추천", "세트", "묶음"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 17,
        icon: "🔥",
        theme: "긴급성 만들기",
        strategy: "Urgency & Scarcity",
        description: "지금 당장 결정하지 않으면 놓칠 것 같은 긴박감을 만들어보세요.",
        tip: "\"오늘 밤 12시까지만\" — 마감 시간을 명확히 하면 행동 전환율이 올라가요.",
        keywords: ["지금", "오늘", "내일", "마감", "얼마 안 남았", "서둘러", "빨리"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 18,
        icon: "🏆",
        theme: "사회적 증거",
        strategy: "Social Proof",
        description: "많은 사람이 선택한 제품임을 보여주는 증거를 활용해보세요.",
        tip: "\"이미 200명이 선택\" — 남들이 좋다고 하면 더 믿게 되는 심리를 활용해요.",
        keywords: ["인기", "베스트", "선택", "명이", "개나 팔린", "후기", "만족"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 19,
        icon: "🎨",
        theme: "비주얼 임팩트",
        strategy: "Visual Marketing",
        description: "첫눈에 멈추게 만드는 강렬한 시각적 인상을 줄 방법을 생각해보세요.",
        tip: "스크롤을 멈추게 하는 건 카피보다 비주얼이에요. 색감, 구도를 의도적으로 설계하세요.",
        keywords: ["비주얼", "색감", "사진", "디자인", "이미지", "구도", "aesthetic"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 20,
        icon: "😂",
        theme: "유머 코드",
        strategy: "Humor Marketing",
        description: "웃음이 나오는, 가볍고 재미있는 방식으로 제품을 소개해보세요.",
        tip: "웃기면 공유된다. 과장, 반전, 밈 — 재미가 바이럴을 만들어요.",
        keywords: ["ㅋㅋ", "웃긴", "진짜로", "솔직히", "아닌데", "이게맞나", "대박"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 21,
        icon: "🧠",
        theme: "교육형 콘텐츠",
        strategy: "Content Marketing",
        description: "이 제품 카테고리에 대해 유용한 정보를 제공하면서 자연스럽게 홍보해보세요.",
        tip: "\"몰랐던 사실\" 형식은 저장율이 높아요. 정보를 주면 팔지 않아도 사게 돼요.",
        keywords: ["몰랐던", "알고보면", "사실", "정보", "팁", "이유", "왜"],
        bonusXP: 50,
        bonusPoints: 32000,
    },
    {
        id: 22,
        icon: "🗺️",
        theme: "고객 여정 설계",
        strategy: "Customer Journey",
        description: "이 제품을 처음 알게 되는 순간부터 구매까지의 흐름을 콘텐츠로 표현해보세요.",
        tip: "인지 → 관심 → 고민 → 구매. 어떤 단계의 고객을 공략하는 콘텐츠인지 생각해보세요.",
        keywords: ["처음", "알게 됐어", "고민하다가", "결국", "샀어", "구매"],
        bonusXP: 55,
        bonusPoints: 35000,
    },
    {
        id: 23,
        icon: "💎",
        theme: "가치 제안 명확화",
        strategy: "Unique Value Proposition",
        description: "이 제품만이 줄 수 있는 딱 한 가지 차별점을 명확하게 전달해보세요.",
        tip: "\"다른 제품과 달리\" — 비교를 통한 차별화가 선택의 이유가 돼요.",
        keywords: ["유일", "다른", "차별", "특별", "오직", "유일하게", "독보적"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 24,
        icon: "👥",
        theme: "커뮤니티 소속감",
        strategy: "Community Marketing",
        description: "이 제품을 쓰는 사람들이 어떤 공통된 가치를 가진 사람들인지 표현해보세요.",
        tip: "\"이 가방 드는 사람들은\" — 소속감이 브랜드 팬덤을 만들어요.",
        keywords: ["우리", "같은", "공통", "취향", "사람들", "팬", "커뮤니티"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 25,
        icon: "🕰️",
        theme: "노스탤지어 마케팅",
        strategy: "Nostalgia Marketing",
        description: "추억, 그리움, 어린 시절을 자극하는 감성으로 제품을 연결해보세요.",
        tip: "\"어릴 때 엄마가 사줬던\" — 감정의 기억이 구매 결정을 내립니다.",
        keywords: ["추억", "그때", "어릴", "옛날", "기억", "그리운", "돌아가고"],
        bonusXP: 50,
        bonusPoints: 30000,
    },
    {
        id: 26,
        icon: "🌍",
        theme: "소셜 임팩트",
        strategy: "Social Impact Marketing",
        description: "이 구매가 더 큰 사회적 변화에 기여한다는 메시지를 담아보세요.",
        tip: "구매 = 참여. 소비자를 변화의 주체로 만들어주세요.",
        keywords: ["기여", "변화", "함께", "세상", "사회", "나눔", "임팩트"],
        bonusXP: 50,
        bonusPoints: 32000,
    },
    {
        id: 27,
        icon: "⭐",
        theme: "리뷰 스토리 만들기",
        strategy: "Review Storytelling",
        description: "단순 리뷰가 아닌, 구매 전 고민부터 사용 후 느낀 점까지 스토리로 써보세요.",
        tip: "\"살까 말까 고민했는데 결국...\" — 스토리 있는 리뷰는 구매 결정에 더 영향을 줘요.",
        keywords: ["고민", "결국", "샀는데", "써보니", "후회", "만족", "다시"],
        bonusXP: 45,
        bonusPoints: 28000,
    },
    {
        id: 28,
        icon: "🎊",
        theme: "이벤트/기념일 연계",
        strategy: "Event Marketing",
        description: "특별한 날이나 이벤트와 제품을 연결해서 선물 욕구를 자극해보세요.",
        tip: "\"생일 선물로 완벽한\" — 특별한 날의 소비는 가격 저항이 낮아져요.",
        keywords: ["선물", "생일", "기념일", "이벤트", "축하", "특별한 날", "기념"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 29,
        icon: "🔗",
        theme: "크로스셀링",
        strategy: "Cross-selling",
        description: "이 제품을 구매한 사람이 다음에 살 법한 다른 제품도 함께 추천해보세요.",
        tip: "\"이것도 같이 사면 더 좋아요\" — 연관 구매로 객단가를 높이는 전략이에요.",
        keywords: ["함께", "세트", "이것도", "추천", "같이 사면", "시리즈", "번들"],
        bonusXP: 40,
        bonusPoints: 25000,
    },
    {
        id: 30,
        icon: "💌",
        theme: "개인화 메시지",
        strategy: "Personalization",
        description: "딱 한 사람을 위한 편지처럼 개인적이고 따뜻하게 써보세요.",
        tip: "\"요즘 지친 당신에게\" — 개인적인 느낌이 강할수록 공감대가 커져요.",
        keywords: ["당신", "나에게", "특별히", "이름", "개인", "맞춤", "위해"],
        bonusXP: 55,
        bonusPoints: 35000,
    },
];

/**
 * 오늘 날짜 기준으로 일일 챌린지를 반환합니다.
 * 모든 학생이 같은 날 같은 챌린지를 경험합니다.
 */
export function getTodayChallenge(): DailyChallenge {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now.getTime() - start.getTime();
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
    const idx = (dayOfYear - 1 + DAILY_CHALLENGES.length) % DAILY_CHALLENGES.length;
    return DAILY_CHALLENGES[idx];
}

/**
 * 오늘 자정까지 남은 시간(초)을 반환합니다.
 */
export function getSecondsUntilMidnight(): number {
    const now = new Date();
    const midnight = new Date(now);
    midnight.setHours(24, 0, 0, 0);
    return Math.floor((midnight.getTime() - now.getTime()) / 1000);
}
